theme = "catppuccin-mocha"
hide-mouse-cursor-when-typing = true
confirm-before-quit = false

[fonts]
size = 18
features = []
use-drawable-chars = true
symbol-map = []
disable-warnings-not-found = false
additional-dirs = []

[fonts.regular]
family = "Maple Mono"
style = "Normal"
width = "Normal"

[fonts.bold]
family = "Maple Mono"
style = "Normal"
width = "Normal"

[fonts.italic]
family = "Maple Mono"
style = "Italic"
width = "Normal"

[fonts.bold-italic]
family = "Maple Mono"
style = "Italic"
width = "Normal"

[fonts.emoji]
family = "Noto Color Emoji"

[editor]
program = "helix"
args = []

[cursor]
shape = "block"
blinkig = false

[window]
opacity = 1
blur = true
