# =============================================================================
# Language Server Configurations
# =============================================================================

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
# === CARGO CONFIGURATION ===
cargo.allFeatures = true
cargo.buildScripts.enable = true
cargo.buildScripts.rebuildOnSave = true
cargo.buildScripts.useRustcWrapper = true
cargo.loadOutDirsFromCheck = true
cargo.autoreload = true
cargo.allTargets = true
# === ADVANCED CHECKING ===
check.command = "clippy"
check.workspace = true
check.allTargets = true
check.extraArgs = [
  "--",
  "-W",
  "clippy::all",
  "-W",
  "clippy::pedantic",
  "-W",
  "clippy::nursery",
  "-W",
  "clippy::cargo",
  "-A",
  "clippy::module_name_repetitions",
  "-A",
  "clippy::missing_errors_doc",
  "-A",
  "clippy::missing_panics_doc",
]
checkOnSave = true
# === COMPLETION ENHANCEMENTS ===
completion.addCallArgumentSnippets = true
completion.addCallParenthesis = true
completion.autoimport.enable = true
completion.postfix.enable = true
completion.privateEditable.enable = true
completion.fullFunctionSignatures.enable = true
completion.callable.snippets = "fill_arguments"
completion.termSearch.enable = true
completion.termSearch.fuel = 2000
# === DIAGNOSTICS & ERROR HANDLING ===
diagnostics.enable = true
diagnostics.enableExperimental = true
diagnostics.disabled = ["unresolved-proc-macro", "unresolved-method"]
diagnostics.styleLints.enable = true
# === HOVER & DOCUMENTATION ===
hover.actions.debug = true
hover.actions.enable = true
hover.actions.gotoTypeDef = true
hover.actions.implementations = true
hover.actions.references = true
hover.actions.run = true
hover.documentation.enable = true
hover.documentation.keywords.enable = true
hover.links.enable = true
hover.memoryLayout.enable = true
hover.memoryLayout.alignment = "hexadecimal"
hover.memoryLayout.offset = "hexadecimal"
hover.memoryLayout.size = "both"
hover.show.enumVariants = 10
hover.show.fields = 10
hover.show.traitAssocItems = 10
# === COMPREHENSIVE INLAY HINTS ===
inlayHints.bindingModeHints.enable = true
inlayHints.chainingHints.enable = true
inlayHints.closingBraceHints.enable = true
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureCaptureHints.enable = true
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.closureStyle = "impl_fn"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.expressionAdjustmentHints.enable = "never"
inlayHints.genericParameterHints.const.enable = true
inlayHints.genericParameterHints.lifetime.enable = true
inlayHints.genericParameterHints.type.enable = true
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.lifetimeElisionHints.useParameterNames = true
inlayHints.maxLength = 30
inlayHints.parameterHints.enable = true
inlayHints.rangeExclusiveHints.enable = true
inlayHints.renderColons = true
inlayHints.typeHints.enable = true
inlayHints.typeHints.hideClosureInitialization = false
inlayHints.typeHints.hideNamedConstructor = false
inlayHints.implicitDrops.enable = false
# === CODE LENS FEATURES ===
lens.debug.enable = true
lens.enable = true
lens.implementations.enable = true
lens.location = "above_name"
lens.references.adt.enable = true
lens.references.enumVariant.enable = true
lens.references.method.enable = true
lens.references.trait.enable = true
lens.run.enable = true
# === PROCEDURAL MACROS ===
procMacro.enable = true
procMacro.attributes.enable = true
procMacro.ignored = { leptos_macro = ["server"] }
# === IMPORTS & FORMATTING ===
imports.granularity.enforce = false
imports.granularity.group = "crate"
imports.group.enable = true
imports.merge.glob = true
imports.prefix = "by_crate"
# === ASSISTS & REFACTORING ===
assist.emitMustUse = true
assist.expressionFillDefault = "default"
assist.preferSelf = true
assist.termSearch.borrowcheck = true
assist.termSearch.fuel = 2000
# === WORKSPACE & PERFORMANCE ===
cachePriming.enable = true
cachePriming.numThreads = 0
lru.capacity = 256
# === SEMANTIC HIGHLIGHTING ===
semanticHighlighting.nonStandardTokens = true
semanticHighlighting.operator.enable = true
semanticHighlighting.operator.specialization.enable = true
semanticHighlighting.punctuation.enable = true
semanticHighlighting.punctuation.specialization.enable = true
semanticHighlighting.strings.enable = true
# === REFERENCES & NAVIGATION ===
references.excludeImports = false
references.excludeTests = false
# === RUNTIME & TESTING ===
runnables.extraArgs = ["--release"]
runnables.extraTestBinaryArgs = ["--show-output", "--nocapture"]
# === WORKSPACE SYMBOLS ===
workspace.symbol.search.scope = "workspace_and_dependencies"
workspace.symbol.search.kind = "all_symbols"
workspace.symbol.search.limit = 256
workspace.symbol.search.excludeImports = false
# === RUSTFMT CONFIGURATION ===
rustfmt.extraArgs = []
rustfmt.rangeFormatting.enable = false
# === ADVANCED FEATURES ===
joinLines.joinAssignments = true
joinLines.joinElseIf = true
joinLines.removeTrailingComma = true
joinLines.unwrapTrivialBlock = true
# === HIGHLIGHT RELATED ITEMS ===
highlightRelated.breakPoints.enable = true
highlightRelated.closureCaptures.enable = true
highlightRelated.exitPoints.enable = true
highlightRelated.references.enable = true
highlightRelated.yieldPoints.enable = true
# === SIGNATURE HELP ===
signatureInfo.detail = "full"
signatureInfo.documentation.enable = true
# === FILE WATCHER ===
files.watcher = "server"

# =============================================================================
# Go Language Server
# =============================================================================

[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
staticcheck = true
completeUnimported = true
matcher = "Fuzzy"
usePlaceholders = true
experimentalPostfixCompletions = true
semanticTokens = true

[language-server.gopls.config.analyses]
unusedparams = true
unusedvariable = true
useany = true

[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
compositeLiteralTypes = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

# =============================================================================
# =============================================================================

[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]

[language-server.vtsls.config]
javascript.tsserver.maxTsServerMemory = 8092
javascript.inlayHints.parameterNames.enabled = "all"
javascript.inlayHints.parameterNames.suppressWhenArgumentMatchesName = false
javascript.inlayHints.parameterTypes.enabled = true
javascript.inlayHints.variableTypes.enabled = true
javascript.inlayHints.variableTypes.suppressWhenTypeMatchesName = false
javascript.inlayHints.propertyDeclarationTypes.enabled = true
javascript.inlayHints.functionLikeReturnTypes.enabled = true
javascript.inlayHints.enumMemberValues.enabled = true
javascript.suggest.autoImports = true
javascript.suggest.completeFunctionCalls = true
javascript.suggest.includeCompletionsForModuleExports = true
javascript.suggest.includeCompletionsWithInsertText = true
javascript.updateImportsOnFileMove.enabled = "always"
javascript.preferences.importModuleSpecifier = "relative"
javascript.preferences.quoteStyle = "single"
typescript.tsserver.maxTsServerMemory = 8092
typescript.inlayHints.parameterNames.enabled = "all"
typescript.inlayHints.parameterNames.suppressWhenArgumentMatchesName = false
typescript.inlayHints.parameterTypes.enabled = true
typescript.inlayHints.variableTypes.enabled = true
typescript.inlayHints.variableTypes.suppressWhenTypeMatchesName = false
typescript.inlayHints.propertyDeclarationTypes.enabled = true
typescript.inlayHints.functionLikeReturnTypes.enabled = true
typescript.inlayHints.enumMemberValues.enabled = true
typescript.suggest.autoImports = true
typescript.suggest.completeFunctionCalls = true
typescript.suggest.includeCompletionsForModuleExports = true
typescript.suggest.includeCompletionsWithInsertText = true
typescript.updateImportsOnFileMove.enabled = "always"
typescript.preferences.importModuleSpecifier = "relative"
typescript.preferences.quoteStyle = "single"

# =============================================================================
# ESLint Language Server
# =============================================================================

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
workingDirectory.mode = "auto"
codeActionOnSave.enable = true
codeActionOnSave.mode = "all"
format.enable = true

# =============================================================================
# Tailwind CSS Language Server
# =============================================================================

[language-server.tailwind-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

# =============================================================================
# Java Language Server (jdtls)
# =============================================================================

[language-server.jdtls]
command = "jdtls"

[language-server.jdtls.config]
bundles = []
java.errors.incompleteClasspath.severity = "warning"
java.configuration.updateBuildConfiguration = "automatic"
java.trace.server = "off"
java.import.gradle.enabled = true
java.import.gradle.wrapper.enabled = true
java.import.gradle.offline.enabled = false
java.import.maven.enabled = true
java.import.maven.offline.enabled = false
java.import.exclusions = [
  "**/node_modules/**",
  "**/.metadata/**",
  "**/archetype-resources/**",
  "**/META-INF/maven/**",
  "/**/test/**"
]
java.jdt.ls.lombokSupport.enabled = true
java.jdt.ls.protobufSupport.enabled = false
java.referencesCodeLens.enabled = true
java.signatureHelp.enabled = true
java.signatureHelp.description.enabled = true
java.implementationsCodeLens.enabled = true
java.format.enabled = true
java.format.comments.enabled = true
java.format.onType.enabled = true
java.saveActions.organizeImports = true
java.autobuild.enabled = true
java.maxConcurrentBuilds = 1
java.completion.enabled = true
java.completion.guessMethodArguments = true
java.completion.favoriteStaticMembers = [
  "org.junit.Assert.*",
  "org.junit.Assume.*",
  "org.junit.jupiter.api.Assertions.*",
  "org.junit.jupiter.api.Assumptions.*",
  "org.junit.jupiter.api.DynamicContainer.*",
  "org.junit.jupiter.api.DynamicTest.*",
  "org.mockito.Mockito.*",
  "org.mockito.ArgumentMatchers.*",
  "org.mockito.Answers.*"
]
java.completion.filteredTypes = [
  "java.awt.*",
  "com.sun.*",
  "sun.*",
  "jdk.*",
  "org.graalvm.*",
  "io.micrometer.shaded.*"
]
java.completion.importOrder = ["java", "javax", "com", "org"]
java.completion.matchCase = "firstLetter"
java.completion.lazyResolveTextEdit.enabled = true
java.completion.postfix.enabled = true
java.completion.chain.enabled = true
java.foldingRange.enabled = true
java.selectionRange.enabled = true
java.semanticHighlighting.enabled = true
java.codeGeneration.hashCodeEquals.useJava7Objects = true
java.codeGeneration.hashCodeEquals.useInstanceof = true
java.codeGeneration.useBlocks = true
java.codeGeneration.generateComments = false
java.codeGeneration.toString.template = "${object.className} [${member.name()}=${member.value}, ${otherMembers}]"
java.codeGeneration.toString.codeStyle = "STRING_CONCATENATION"
java.codeGeneration.toString.skipNullValues = false
java.codeGeneration.toString.listArrayContents = true
java.codeGeneration.toString.limitElements = 0
java.codeGeneration.insertionLocation = "afterCursor"
java.inlayHints.parameterNames.enabled = "all"
java.inlayHints.parameterNames.exclusions = []
java.compile.nullAnalysis.mode = "automatic"
java.compile.nullAnalysis.nonnull = []
java.compile.nullAnalysis.nullable = []
java.sources.organizeImports.starThreshold = 99
java.sources.organizeImports.staticStarThreshold = 99
java.references.includeAccessors = true
java.references.includeDecompiledSources = true
java.typeHierarchy.lazyLoad = false
java.codeAction.sortMembers.avoidVolatileChanges = true
java.templates.fileHeader = []
java.templates.typeComment = []
java.cleanup.actionsOnSave = []

# =============================================================================
# Kotlin Language Server
# =============================================================================

[language-server.kotlin-lsp]
command = "kotlin-language-server"

# =============================================================================
# Vue Language Server
# =============================================================================

[language-server.vue]
command = "vue-language-server"
args = ["--stdio"]
config = { typescript = { tsdk = "node_modules/typescript/lib/" } }

# =============================================================================
# Python Language Server
# =============================================================================

[language-server.pylsp]
command = "pylsp"

[language-server.pylsp.config.pylsp.plugins]
ruff.enabled = true
ruff.lineLength = 100
ruff.extendSelect = ["I"]

# =============================================================================
# Ruff Language Server (additional for Python)
# =============================================================================

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config.settings]
exclude = ["*"]

# =============================================================================
# Language Overrides
# =============================================================================

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "go"
language-servers = ["gopls"]
auto-format = true
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "typescript"
language-servers = ["vtsls", "eslint", "tailwind-ls"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "tsx"
language-servers = ["vtsls", "eslint", "tailwind-ls"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "javascript"
language-servers = ["vtsls", "eslint"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "jsx"
language-servers = ["vtsls", "eslint"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "json"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "yaml"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "markdown"
auto-format = true
indent = { tab-width = 2, unit = "  " }
soft-wrap.enable = true
text-width = 100

[[language]]
name = "python"
language-servers = ["pylsp", "ruff"]
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "vue"
language-servers = ["vue"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "toml"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "java"
language-servers = ["jdtls"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "kotlin"
language-servers = ["kotlin-lsp"]
auto-format = true
indent = { tab-width = 2, unit = "  " }
