theme = "catppuccin_mocha"

# =============================================================================
# Editor Configuration
# =============================================================================

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
idle-timeout = 0
line-number = "relative"
mouse = true
scrolloff = 999
true-color = true
auto-completion = true
auto-format = true
completion-trigger-len = 2

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-global = false
git-ignore = true
follow-symlinks = true
deduplicate-links = true

[editor.indent-guides]
character = "|"
render = true
skip-levels = 1

[editor.lsp]
display-inlay-hints = true
display-messages = true
auto-signature-help = true
display-signature-help-docs = true
snippets = true

[editor.soft-wrap]
enable = true

[editor.auto-pairs]
'(' = ")"
'{' = "}"
'[' = "]"
'"' = '"'
'`' = "`"

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace.render]
space = "none"
tab = "none"
newline = "none"

# =============================================================================
# Statusline Configuration
# =============================================================================

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = [
  "mode",
  "spacer",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "file-modification-indicator",
]
right = [
  "spinner",
  "spacer",
  "workspace-diagnostics",
  "separator",
  "spacer",
  "diagnostics",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
