theme = "catppuccin_mocha"

# =============================================================================
# Editor Configuration
# =============================================================================

[editor]
bufferline = "multiple"
color-modes = true
idle-timeout = 0
line-number = "relative"
mouse = true
scrolloff = 999
true-color = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
git-global = false # show files hidden by git globally
hidden = false     # show hidden files as in starting with a dot

[editor.indent-guides]
character = "|"
render = true
skip-levels = 1

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = true

# =============================================================================
# Theme & UI
# =============================================================================

[editor.statusline]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"
left = [
  "mode",
  "spacer",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "file-modification-indicator",
]
right = [
  "spinner",
  "spacer",
  "workspace-diagnostics",
  "separator",
  "spacer",
  "diagnostics",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
